apiVersion: apps/v1
kind: Deployment
metadata:
  name:  cal-deployment
  namespace: default
  labels:
    app:  cal-deployment
spec:
  selector:
    matchLabels:
      app: cal-pod
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  cal-pod
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  cal-container
        image:  calculationregistry.azurecr.io/cal-svc:v1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          